# Generated by Django 4.2.1 on 2023-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productPrice', models.DecimalField(decimal_places=1, max_digits=5)),
                ('productCount', models.IntegerField()),
            ],
        ),
    ]
